// VitaScan Design System — Vibrant Glassmorphism

export const Colors = {
  primary: '#ff8c00',
  primaryLight: '#ffb77d',
  primarySoft: '#fff4ea',
  ink: '#1a1a1a',
  snow: '#fcf8f8',
  mint: '#c8f2d3',
  peach: '#ffd9bf',
  lavender: '#e7ddff',
  sky: '#d9f1ff',

  meshPeach: '#ffd9bf',
  meshMint: '#c8f2d3',
  meshBlue: '#d9f1ff',
  meshLavender: '#e7ddff',

  macro: {
    protein: '#3f86cf',
    proteinLight: '#edf5ff',
    proteinGrad: ['#3f86cf', '#88bee8'] as [string, string],
    carbs: '#f2a83b',
    carbsLight: '#fff7ea',
    carbsGrad: ['#f2a83b', '#ffd69e'] as [string, string],
    fat: '#48b76a',
    fatLight: '#effcf3',
    fatGrad: ['#48b76a', '#9de1b1'] as [string, string],
    fiber: '#9464c7',
    fiberLight: '#f7f1ff',
    fiberGrad: ['#9464c7', '#c7b3ee'] as [string, string],
    sugar: '#de5b4f',
    sugarLight: '#fff1ef',
    sugarGrad: ['#de5b4f', '#ffb39f'] as [string, string],
    kcal: '#ff8c00',
    kcalLight: '#fff4ea',
    kcalGrad: ['#ff8c00', '#ffb77d'] as [string, string],
  },

  glass: {
    white: '#ffffff',
    whiteSoft: 'rgba(255, 255, 255, 0.88)',
    whiteStrong: '#ffffff',
    border: 'rgba(26, 26, 26, 0.16)',
    borderSoft: 'rgba(26, 26, 26, 0.1)',
    shadow: 'rgba(26, 26, 26, 0.08)',
  },

  text: {
    primary: '#1a1a1a',
    secondary: '#3f3f46',
    muted: '#76767c',
    white: '#FFFFFF',
    whiteAlpha: 'rgba(255,255,255,0.88)',
  },

  status: {
    verified: '#2ECC71',
    verifiedBg: '#F0FFF4',
    banned: '#E74C3C',
    bannedBg: '#FFF0F0',
    unverified: '#F5A623',
    unverifiedBg: '#FFF8EC',
  },

  bg: {
    light: '#fcf8f8',
    card: '#FFFFFF',
  },

  dashboard: {
    page: '#fcf9f8',
    card: '#ffffff',
    stroke: '#1c1b1b',
    strokeSoft: 'rgba(28,27,27,0.1)',
    shadowHard: '#1c1b1b',
    shadowHardSoft: 'rgba(28,27,27,0.1)',
    blobMint: '#e8f5e9',
    blobPeach: '#ffdad6',
    blobLavender: '#eadecc',
    softGreen: '#e8f5e9',
    softOrange: '#eadecc',
    softBlue: '#e1f5fe',
    kcalTrack: '#f1edec',
    kcalFill: '#ffb77d',
    proteinBg: '#ffffff',
    proteinTrack: '#f0eded',
    proteinFill: '#d0c5b3',
    carbsBg: '#ffffff',
    carbsTrack: '#f0eded',
    carbsFill: '#b6cad2',
    fatBg: '#ffffff',
    fatTrack: '#f0eded',
    fatFill: '#fcd34d',
    nutritionIcon: '#556158',
    waterBg: '#e1f5fe',
    waterIcon: '#b6cad2',
    waterFill: '#0b1e24',
    tabBg: '#fcf9f8',
    tabActive: '#eadecc',
    tabInactive: '#434844',
    secondary: '#655d4f',
    onSecondary: '#ffffff',
    surfaceContainerLow: '#f6f3f2',
    surfaceContainer: '#f0eded',
    surfaceContainerHigh: '#eae7e7',
    surfaceContainerHighest: '#e5e2e1',
    onSurfaceVariant: '#434844',
    outlineVariant: '#c3c8c2',
    tertiaryFixed: '#d2e6ef',
    primaryFixed: '#d9e6da',
    errorContainer: '#ffdad6',
    secondaryContainer: '#eadecc',
  },
} as const;

export const Radius = {
  sm: 10,
  md: 16,
  lg: 20,
  xl: 24,
  '2xl': 28,
  '3xl': 36,
  full: 999,
} as const;

export const Spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  '2xl': 24,
  '3xl': 32,
  '4xl': 40,
  '5xl': 48,
  '6xl': 64,
} as const;

export const Typography = {
  hero: { fontSize: 32, fontWeight: '900' as const, letterSpacing: -0.5 },
  title: { fontSize: 24, fontWeight: '800' as const },
  subtitle: { fontSize: 18, fontWeight: '700' as const },
  body: { fontSize: 15, fontWeight: '400' as const },
  bodyMedium: { fontSize: 15, fontWeight: '600' as const },
  caption: { fontSize: 12, fontWeight: '500' as const },
  label: { fontSize: 13, fontWeight: '600' as const },
  number: { fontSize: 48, fontWeight: '900' as const, letterSpacing: -1 },
  numberSm: { fontSize: 28, fontWeight: '800' as const },
} as const;
